### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by tanyaivat** [tanyaivat/pr4_2020#1]
Знайти найкраще фото в Інтернеті

**Comment by tanyaivat1** [comment]
Вже шукаю

**Comment by tanyaivat1** [comment]
![image](https://user-images.githubusercontent.com/74207537/98586742-d27f4f00-22d1-11eb-9e68-a8118e5644d1.png)

**Comment by tanyaivat1** [comment]
Зображення знайдено
